#
# See https://github.com/elechouse/PN532/blob/PN532_HSU/PN532/PN532.h
#
from micropython import const

PN532_COMMAND_DIAGNOSE              = const(0x00)
PN532_COMMAND_GETFIRMWAREVERSION    = const(0x02)
PN532_COMMAND_GETGENERALSTATUS      = const(0x04)
PN532_COMMAND_READREGISTER          = const(0x06)
PN532_COMMAND_WRITEREGISTER         = const(0x08)
PN532_COMMAND_READGPIO              = const(0x0C)
PN532_COMMAND_WRITEGPIO             = const(0x0E)
PN532_COMMAND_SETSERIALBAUDRATE     = const(0x10)
PN532_COMMAND_SETPARAMETERS         = const(0x12)
PN532_COMMAND_SAMCONFIGURATION      = const(0x14)
PN532_COMMAND_POWERDOWN             = const(0x16)
PN532_COMMAND_RFCONFIGURATION       = const(0x32)
PN532_COMMAND_RFREGULATIONTEST      = const(0x58)
PN532_COMMAND_INJUMPFORDEP          = const(0x56)
PN532_COMMAND_INJUMPFORPSL          = const(0x46)
PN532_COMMAND_INLISTPASSIVETARGET   = const(0x4A)
PN532_COMMAND_INATR                 = const(0x50)
PN532_COMMAND_INPSL                 = const(0x4E)
PN532_COMMAND_INDATAEXCHANGE        = const(0x40)
PN532_COMMAND_INCOMMUNICATETHRU     = const(0x42)
PN532_COMMAND_INDESELECT            = const(0x44)
PN532_COMMAND_INRELEASE             = const(0x52)
PN532_COMMAND_INSELECT              = const(0x54)
PN532_COMMAND_INAUTOPOLL            = const(0x60)
PN532_COMMAND_TGINITASTARGET        = const(0x8C)
PN532_COMMAND_TGSETGENERALBYTES     = const(0x92)
PN532_COMMAND_TGGETDATA             = const(0x86)
PN532_COMMAND_TGSETDATA             = const(0x8E)
PN532_COMMAND_TGSETMETADATA         = const(0x94)
PN532_COMMAND_TGGETINITIATORCOMMAND = const(0x88)
PN532_COMMAND_TGRESPONSETOINITIATOR = const(0x90)
PN532_COMMAND_TGGETTARGETSTATUS     = const(0x8A)

PN532_RESPONSE_INDATAEXCHANGE       = const(0x41)
PN532_RESPONSE_INLISTPASSIVETARGET  = const(0x4B)


PN532_MIFARE_ISO14443A              = const(0x00)

# Mifare Commands
MIFARE_CMD_AUTH_A                   = const(0x60)
MIFARE_CMD_AUTH_B                   = const(0x61)
MIFARE_CMD_READ                     = const(0x30)
MIFARE_CMD_WRITE                    = const(0xA0)
MIFARE_CMD_WRITE_ULTRALIGHT         = const(0xA2)
MIFARE_CMD_TRANSFER                 = const(0xB0)
MIFARE_CMD_DECREMENT                = const(0xC0)
MIFARE_CMD_INCREMENT                = const(0xC1)
MIFARE_CMD_STORE                    = const(0xC2)

# FeliCa Commands
FELICA_CMD_POLLING                  = const(0x00)
FELICA_CMD_REQUEST_SERVICE          = const(0x02)
FELICA_CMD_REQUEST_RESPONSE         = const(0x04)
FELICA_CMD_READ_WITHOUT_ENCRYPTION  = const(0x06)
FELICA_CMD_WRITE_WITHOUT_ENCRYPTION = const(0x08)
FELICA_CMD_REQUEST_SYSTEM_CODE      = const(0x0C)

# Prefixes for NDEF Records (to identify record type)
NDEF_URIPREFIX_NONE                 = const(0x00)
NDEF_URIPREFIX_HTTP_WWWDOT          = const(0x01)
NDEF_URIPREFIX_HTTPS_WWWDOT         = const(0x02)
NDEF_URIPREFIX_HTTP                 = const(0x03)
NDEF_URIPREFIX_HTTPS                = const(0x04)
NDEF_URIPREFIX_TEL                  = const(0x05)
NDEF_URIPREFIX_MAILTO               = const(0x06)
NDEF_URIPREFIX_FTP_ANONAT           = const(0x07)
NDEF_URIPREFIX_FTP_FTPDOT           = const(0x08)
NDEF_URIPREFIX_FTPS                 = const(0x09)
NDEF_URIPREFIX_SFTP                 = const(0x0A)
NDEF_URIPREFIX_SMB                  = const(0x0B)
NDEF_URIPREFIX_NFS                  = const(0x0C)
NDEF_URIPREFIX_FTP                  = const(0x0D)
NDEF_URIPREFIX_DAV                  = const(0x0E)
NDEF_URIPREFIX_NEWS                 = const(0x0F)
NDEF_URIPREFIX_TELNET               = const(0x10)
NDEF_URIPREFIX_IMAP                 = const(0x11)
NDEF_URIPREFIX_RTSP                 = const(0x12)
NDEF_URIPREFIX_URN                  = const(0x13)
NDEF_URIPREFIX_POP                  = const(0x14)
NDEF_URIPREFIX_SIP                  = const(0x15)
NDEF_URIPREFIX_SIPS                 = const(0x16)
NDEF_URIPREFIX_TFTP                 = const(0x17)
NDEF_URIPREFIX_BTSPP                = const(0x18)
NDEF_URIPREFIX_BTL2CAP              = const(0x19)
NDEF_URIPREFIX_BTGOEP               = const(0x1A)
NDEF_URIPREFIX_TCPOBEX              = const(0x1B)
NDEF_URIPREFIX_IRDAOBEX             = const(0x1C)
NDEF_URIPREFIX_FILE                 = const(0x1D)
NDEF_URIPREFIX_URN_EPC_ID           = const(0x1E)
NDEF_URIPREFIX_URN_EPC_TAG          = const(0x1F)
NDEF_URIPREFIX_URN_EPC_PAT          = const(0x20)
NDEF_URIPREFIX_URN_EPC_RAW          = const(0x21)
NDEF_URIPREFIX_URN_EPC              = const(0x22)
NDEF_URIPREFIX_URN_NFC              = const(0x23)

PN532_GPIO_VALIDATIONBIT            = const(0x80)
PN532_GPIO_P30                      = const(0)
PN532_GPIO_P31                      = const(1)
PN532_GPIO_P32                      = const(2)
PN532_GPIO_P33                      = const(3)
PN532_GPIO_P34                      = const(4)
PN532_GPIO_P35                      = const(5)

# FeliCa consts
FELICA_READ_MAX_SERVICE_NUM         = const(16)
FELICA_READ_MAX_BLOCK_NUM           = const(12) # for typical FeliCa card
FELICA_WRITE_MAX_SERVICE_NUM        = const(16)
FELICA_WRITE_MAX_BLOCK_NUM          = const(10) # for typical FeliCa card
FELICA_REQ_SERVICE_MAX_NODE_NUM     = const(32)
